const questions = [
  [
    'https://picsum.photos/1920/1080',
    'Who was a renowned Indian leader in the struggle for independence from British rule and is often referred to as the "Father of the Nation"?',
    [
      'Mahatma Gandhi',
      'Jawaharlal Nehru',
      'Sardar Patel',
      'Subhas Chandra Bose',
      'B.R. Ambedkar',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Chinese-American physicist is known for their groundbreaking work in nuclear physics and won the inaugural Wolf Prize in Physics?',
    [
      'Chien-Shiung Wu',
      'Yuan T. Lee',
      'Steven Chu',
      'Chen-Ning Yang',
      'Tsung-Dao Lee',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Chinese-American architect behind iconic buildings like the Louvre Pyramid in Paris and the National Gallery of Art East Building in Washington, D.C.?',
    ['Maya Lin', 'I. M. Pei', 'Tadao Ando', 'Frank Gehry', 'Norman Foster'],
    1,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Indian-American economist and Nobel laureate is known for his work in the field of development economics and his book "Good Economics for Hard Times".',
    [
      'Raghuram Rajan',
      'Amartya Sen',
      'Abhijit Banerjee',
      'Duflo Esther',
      'Manmohan Singh',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Chinese-American computer scientist and entrepreneur co-founded Yahoo! and is a prominent figure in the tech industry.',
    ['Steve Chen', 'Andrew Ng', 'Jerry Yang', 'Richard Yu', 'Jack Ma'],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Indian-American author and surgeon wrote the bestselling memoir "When Breath Becomes Air" about his battle with terminal cancer.',
    [
      'Atul Gawande',
      'Abraham Verghese',
      'Sandeep Jauhar',
      'Paul Kalanithi',
      'Deepak Chopra',
    ],
    3,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who was a Chinese-American martial artist, actor, and filmmaker best known for his role in "Enter the Dragon" and his contributions to the popularization of martial arts in the West?',
    ['Jet Li', 'Jackie Chan', 'Donnie Yen', 'Chuck Norris', 'Bruce Lee'],
    4,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Filipino-American singer and actress is known for her roles in Broadway musicals like "Miss Saigon" and "Les Misérables"?',
    [
      'Nina Zatulini',
      'Regine Velasquez',
      'Lea Salonga',
      'Lani Misalucha',
      'Charice Pempengco',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who was a Chinese-American labor leader and civil rights activist who co-founded the Asian Americans for Equal Opportunity and played a key role in fighting for the rights of Asian-Americans?',
    [
      'Grace Lee Boggs',
      'Yuri Kochiyama',
      'Helen Zia',
      'Suyin Haynes',
      'Maxine Hong Kingston',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Indian-American physician and astronaut became the first person of Indian descent in space and later served as the Surgeon General of the United States?',
    [
      'Kalpana Chawla',
      'Sunita Williams',
      'Rakesh Sharma',
      'Naveen Jain',
      'Vandana Shiva',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Chinese-American fashion designer known for her eponymous brand and for her role as a judge on the reality TV show "Project Runway"?',
    [
      'Vera Wang',
      'Anna Sui',
      'Tom Ford',
      'Donatella Versace',
      'Diane von Fürstenberg',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Japanese-American actor is famous for his role as Sulu on the original "Star Trek" series and for his LGBTQ+ activism.',
    [
      'James Shigeta',
      'Sessue Hayakawa',
      'George Takei',
      'Pat Morita',
      'Jack Soo',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Indian-American CEO of Alphabet Inc. and its subsidiary, Google, and is known for his contributions to the development of the Android operating system?',
    [
      'Sundar Pichai',
      'Rajat Gupta',
      'Arvind Krishna',
      'Shantanu Narayen',
      'Indra Nooyi',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Filipino-American labor leader and co-founder of the United Farm Workers (UFW) was known for his leadership in the Delano grape strike.',
    [
      'Philip Vera Cruz',
      'Larry Itliong',
      'Cesar Chavez',
      'Benigno Aquino Jr.',
      'Ferdinand Marcos',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Chinese-American actress starred in the film "Crazy Rich Asians" and is also known for her role in the TV series "Fresh Off the Boat"?',
    ['Lucy Liu', 'Ming-Na Wen', 'Constance Wu', 'Michelle Yeoh', 'Sandra Oh'],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who was a Japanese-American designer and architect known for his innovative designs of the Guggenheim Museum in New York and the Disney Concert Hall in Los Angeles?',
    [
      'Kenzo Tange',
      'I. M. Pei',
      'Fumihiko Maki',
      'Isamu Noguchi',
      'Frank Gehry',
    ],
    4,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Indian-American comedian and actor is best known for his role in the TV show "The Office" and as the creator of "Never Have I Ever" on Netflix.',
    [
      'Kunal Nayyar',
      'Aziz Ansari',
      'Kumail Nanjiani',
      'Mindy Kaling',
      'Hasan Minhaj',
    ],
    3,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Filipino-American singer and songwriter behind the hit songs "Versace on the Floor" and "Locked Out of Heaven"?',
    [
      'Arnel Pineda',
      'Jose Mari Chan',
      'Bruno Mars',
      'Lea Salonga',
      'Gary Valenciano',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Chinese-American astronaut became the first Asian-American in space and later served as the Administrator of NASA.',
    [
      'Yuri Malenchenko',
      'Leroy Chiao',
      'Ellen Ochoa',
      'Charles Bolden',
      'Eileen Collins',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who was the Indian-American astronaut who became the first person of Indian descent in space and is known for his contributions to the International Space Station (ISS)?',
    [
      'Sunita Williams',
      'Kalpana Chawla',
      'Rakesh Sharma',
      'Naveen Jain',
      'Vandana Shiva',
    ],
    1,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Japanese-American actor starred in classic films like "Mr. Baseball" and "Karate Kid" and was known for his martial arts expertise?',
    [
      'Yul Brynner',
      'George Takei',
      'Pat Morita',
      'Sessue Hayakawa',
      'Jack Soo',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Chinese-American tech entrepreneur co-founded the social media platform Reddit and later became a prominent advocate for internet freedom.',
    [
      'Mark Zuckerberg',
      'Jack Dorsey',
      'Steve Chen',
      'Aaron Swartz',
      'Steve Huffman',
    ],
    2,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Indian-American author of the novel "Interpreter of Maladies," which won the Pulitzer Prize for Fiction in 2000?',
    [
      'Jhumpa Lahiri',
      'Arundhati Roy',
      'Kiran Desai',
      'Chetan Bhagat',
      'Salman Rushdie',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Japanese-American figure skater became the first woman of Asian descent to win an Olympic gold medal in figure skating.',
    [
      'Michelle Kwan',
      'Kristi Yamaguchi',
      'Tara Lipinski',
      'Yuna Kim',
      'Mao Asada',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Filipino-American actress known for her role in the TV series "Ugly Betty" and for voicing the character of Princess Anna in Disney\'s "Frozen"?',
    [
      'Anna Maria Perez de Tagle',
      'Nicole Scherzinger',
      'Maja Salvador',
      'Regine Velasquez',
      'Lea Salonga',
    ],
    4,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Chinese-American physicist shared the Nobel Prize in Physics for their experimental work on parity non-conservation in weak nuclear interactions?',
    [
      'Chien-Shiung Wu',
      'Steven Chu',
      'Chen-Ning Yang',
      'Tsung-Dao Lee',
      'Richard Feynman',
    ],
    0,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Indian-American actress and comedian is known for her role in the TV series "The Mindy Project" and as the creator of "Never Have I Ever" on Netflix.',
    [
      'Kunal Nayyar',
      'Aziz Ansari',
      'Kumail Nanjiani',
      'Mindy Kaling',
      'Hasan Minhaj',
    ],
    3,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Filipino-American singer, actress, and model known for her hits like "In My Feelings" and her appearances in the TV series "Riverdale"?',
    [
      'Janina San Miguel',
      'Kelsey Merritt',
      'Maymay Entrata',
      'Liza Soberano',
      'Nadine Lustre',
    ],
    3,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Which Chinese-American fashion designer is known for her luxury fashion house and her iconic wrap dress?',
    [
      'Anna Sui',
      'Vera Wang',
      'Donatella Versace',
      'Diane von Fürstenberg',
      'Tory Burch',
    ],
    1,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who was a prominent Indian-American astronaut and the first woman of Indian descent in space, known for her contributions to various space missions and research?',
    [
      'Kalpana Chawla',
      'Sunita Williams',
      'Ellen Ochoa',
      'Rakesh Sharma',
      'Eileen Collins',
    ],
    1,
  ],
  [
    'https://picsum.photos/1920/1080',
    'This Japanese-American actor gained fame for his role as Hiro Nakamura in the TV series "Heroes" and as the voice of Sylar in "Spider-Man: Into the Spider-Verse".',
    [
      'George Takei',
      'Masi Oka',
      'Pat Morita',
      'Sessue Hayakawa',
      'James Shigeta',
    ],
    1,
  ],
  [
    'https://picsum.photos/1920/1080',
    'Who is the Filipino-American journalist and TV news anchor known for her work with ABC News and for her contributions to "The View" as a co-host?',
    [
      'Gloria Diaz',
      'Korina Sanchez',
      'Jessica Soho',
      'Maria Ressa',
      'Roberta Roldan',
    ],
    3,
  ],
];
